### ISSUE TITLE
Allow using a tweets archive file

### ISSUE THREAD

**Issue by rafitamolin** [tommeagher/heroku_ebooks#48]
In the original [twitter_ebooks](https://github.com/mispy/twitter_ebooks) bot, there's an option to download and then incrementally update a local json archive of a user's tweets, and also to convert the .csv file of your Twitter Archive files to .json so it can properly work.

It would be nice to allow someone to manually [download their twitter archive](https://help.twitter.com/en/managing-your-account/how-to-download-your-twitter-archive) and then converting the included tweets.csv in the archive to a .json file that the bot can read and publish tweets with.

**Comment by tommeagher** [comment]
@rafitamolin This is a very interesting idea. I'd be open to a pull request if someone wants to try to tackle this feature.

**Comment by TimLChan** [comment]
I've done a [rudamentary](https://github.com/TimLChan/heroku_ebooks/blob/master/twittereater.py) parser which allows you to extract the tweets from the twitter archive and place them in a CSV, but I've done a few commits since then.

If I find some time, I'll create a branch and pick out the commit and raise a PR
